### Create Support
POST http://localhost:3000/api/support
Content-Type: application/json

{
    "comment": "Prueba de soporte técnico",
    "id_user": 1,
    "id_ticket": 1
}

###


### List Support

GET http://localhost:3000/api/support

###


### Update Support By ID

PATCH http://localhost:3000/api/support/1
Content-Type: application/json

{
    "comment": "PruebaAprobada"
}

###


### Delete Support By ID

DELETE http://localhost:3000/api/support/1

###



### Search Support By ID

GET http://localhost:3000/api/support/1

###